// AUTO-GENERATED by scripts/gen_build_info.sh — do not edit manually.
// Re-generated before every build via the build scripts and CI workflows.
// ignore_for_file: constant_identifier_names

const String kBuildGitHash = 'dc97f3a';
const String kBuildGitHashFull = 'dc97f3a73c0a9a30b1f995a4d1a06fc16ce76541';
const String kBuildTimestamp = '2026-06-12T16:24:42Z';
