#!/usr/bin/env bash
# Generate lib/build_info.dart with the current git hash and timestamp.
# Run before `flutter build` — called by build_macos.sh, build_linux.sh,
# release.yml, and deploy-web.yml.
set -euo pipefail

cd "$(dirname "$0")/.."

SHORT=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
FULL=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat > lib/build_info.dart <<EOF
// AUTO-GENERATED by scripts/gen_build_info.sh — do not edit manually.
// Re-generated before every build via the build scripts and CI workflows.
// ignore_for_file: constant_identifier_names

const String kBuildGitHash = '$SHORT';
const String kBuildGitHashFull = '$FULL';
const String kBuildTimestamp = '$TS';
EOF

echo "gen_build_info: $SHORT ($TS)"
